database:
  # Database connection settings
  host: localhost
  port: 3306
  name: lov4craft
  username: root
  password: ''
  
  # Connection pool settings
  pool:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 300000
    connection-timeout: 10000
    max-lifetime: 600000
    
  # Table prefix for all plugin tables
  table-prefix: lov4craft_
